export const SWAGGER_API_TAG = {
  AUTH: 'AUTH',
  USER: 'USER',
  INVENTORY: 'INVENTORY',
  RESULTS: 'RESULTS',
  SPORTS: 'SPORTS',
  REGISTRATION: 'REGISTRATION',
  ADDFIXTURES: 'ADDFIXTURES',
  FIXTURES: 'FIXTURES',
  HIRING: 'HIRING',
};
